### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/lyricsapi#2]
As mentioned by @devlocalhost in https://github.com/raitonoberu/sptlrx/issues/30, the API needs to be more verbose. The problem is that now we can't determine if the API is working or if the lyrics of the song are simply not found. We can't edit the response body because it would break backward compatibility, but it is certainly possible to send different status codes or put messages in the header.

**Comment by devlocalhost** [comment]
> As mentioned by @devlocalhost in [raitonoberu/sptlrx#30](https://github.com/raitonoberu/sptlrx/issues/30), the API needs to be more verbose. The problem is that now we can't determine if the API is working or if the lyrics of the song are simply not found. We can't edit the response body because it would break backward compatibility, but it is certainly possible to send different status codes or put messages in the header.

1
> we can't determine if the API is working

lyricsapi, or Spotify?

2
>  the lyrics of the song are simply not found

This should be easy to test. Spotify uses Musixmatch for lyrics. Check if some songs have lyrics on Musixmatch. If they don't, you can get the track id, and use lyricsapi. If it returns an empty list, then that means no lyrics. Before returning the lyrics, you can check if there is lyrics at all, and as you said:
> it is certainly possible to send different status codes

You could send a 200 status code, indicating that everything went well, and 404 if there are no lyrics, and maybe a helpful message

You can maybe take inspiration from my lyrics API: https://github.com/devlocalhost/pylyrical_api/blob/ab753b9aaa9238f0b61ac07c150131b0e462f8ff/serv.py#L92

**Comment by raitonoberu** [comment]
now it works this way:
- status code 200 - everything is fine - the lyrics are returned
- status code 404 - the lyrics were not found - empty array is returned
- status code 500 - internal error - empty array is returned - see the "error" header field
